#!/bin/bash
#####################################################################
# Script Name  : archive-bank
# Description  : archives HomeBank 5.2.3 backup files from the previous month
# Dependencies : date, find, mv, rm, touch, zip
# Arguments    : none
# Author       : Richard Romig, 31 January 2019
# Email        : rick.romig@gmail.com
# Comment      : Run on the last date of the month!
# Script will not run prior to the 21st day of the month.
#####################################################################

# Determine the current month and day
month=$(date +"%b")
today=$(date +"%d")
# set value of runit. 0 = okay to run script, 1 = not okay
runit=1

# check if it's the last day of the month
case $month in
	Feb)
		[ "$today" -ge "28" ] && runit=0;;
	Apr|Jun|Sep|Nov)
		[ "$today" -eq "30" ] && runit=0;;
	*)
		[ "$today" -eq "31" ] && runit=0;;
esac

# if not the last day of the month
if [ "$runit" -eq "1" ] && [ "$today" -lt "21" ]; then
	echo "$month $today is too early in the month to archive last month's backup files."
	echo "Archive operation canceled."
	exit 1
elif [ "$runit" -eq "1" ]; then
	echo "$month $today is not the end of the month."
	read -p "Do you sitll wish to archive last month's backup files? " yn
	case $yn in
		[Yy]*)
			echo "Archiving last month's backup files...";;
		*)
			echo "Archive operation canceled."
			exit 1
			;;
	esac
fi

# Execute the arhive operation

# store the directory where script was launched
curdir=$PWD

# set reference date to 1 minute after midnight on 1st day of the current month
# and create the temporary reference file
rd=$(date +"%Y%m")
rd+="010001"
touch -t $rd /tmp/homebank.txt 2>/dev/null
if [ "$?" -ne "0" ]; then
	echo "Error: Could not create /tmp/homebank.txt"
	exit 1
fi

# go to HomeBank directory from wherever you are if you're not already there
[ "$curdir" != "~/Documents/HomeBank" ] && pushd ~/Documents/HomeBank/ > /dev/null

# create the backup and archive folders if they don't already exist
[ ! -d ~/Documents/HomeBank/backup ] && mkdir -p ~/Documents/HomeBank/backup
[ ! -d ~/Documents/HomeBank/archive ] && mkdir -p ~/Documents/HomeBank/archive

echo "Archiving HomeBank backup files from the previous calendar month..."

# move backup files from the previous month to the backup folder
find ./ -maxdepth 1 -type f -iname "*.bak" -not -newer /tmp/homebank.txt -exec mv '{}' backup/ \;

# Check for files in the backup directory
if [ "$(ls -A backup)" ]; then
	hbarchive=$(date --date="40 days ago" +"%Y-%m")
	hbarchive+="-backup.zip"
	cd backup/
	zip $hbarchive *.bak
	mv $hbarchive ../archive/
	rm *.bak
	cd ..
	echo "HomeBank backup files for previous calendar month archived."
else
	echo "No previous calendar month backup files available to be archived."
fi

rm /tmp/homebank.txt

# go back to wherever you started
[ "$curdir" != "~/Documents/HomeBank" ] && popd > /dev/null

exit 0
