#!/bin/bash
###############################################################################
# Script Name  : hb-late
# Description  : Create HomeBank archive after the end of the month.
# Dependencies : zip
# Arguments    :
# Author       : Richard B. Romig, 02 September 2019
# Email        : rick.romig@gmail.com
# Comments     :
# TODO (rick)  :
###############################################################################
# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

# Variables

readonly SCRIPT=$(basename "$0"
readonly VERSION="0.0.4"
readonly UPDATED="13 September 2019"

readonly CURDIR=$PWD
readonly HBDIR=$HOME"/Documents/HomeBank"

# Previous month (2 calendar months)
PREVMONTH=$(date -d "$(date +%Y-%m-01) - 2 months" +"%B %Y")

# Set reference date to the first day of the previous month
REFDATE=$(date -d "$(date +%Y-%m-01) - 1 month" +%m%d%Y)

# Create filename for the archive file
HBARCHIVE=$(date -d "$(date +%Y-%m-01) - 2 months" +%Y-%m)-backup.zip

[ "$CURDIR" != "$HBDIR" ] && pushd "$HBDIR" > /dev/null 2>&1

echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
echo "Archive HomeBank backup files when I forget at the end of the month."

if zip -mtt "$REFDATE" "archive/$HBARCHIVE" ./*.bak 2>/dev/null
then
  echo "HomeBank backup files for $PREVMONTH archived."
  echo "HomeBank Archives:"
  ls -1 archive/
else
  STATUS="$?"
  echo "No backup files for $PREVMONTH available to be archived."
  echo "Zip Error Code: $STATUS" >&2
fi

[ "$CURDIR" != "$HBDIR" ] && popd > /dev/null 2>&1

exit
